# Generated by Django 4.0.5 on 2022-07-23 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('french', '0002_remove_quote_author_user_alter_quote_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='author',
            field=models.CharField(choices=[('Virgile', 'Virgile'), ('Simone Weil', 'Simone Weil'), ('Michel Vinaver', 'Michel Vinaver')], max_length=20),
        ),
    ]
