# Generated by Django 4.0.5 on 2022-07-23 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('french', '0003_alter_quote_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
