# Generated by Django 4.0.5 on 2022-07-24 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('french', '0005_alter_quote_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
