# Generated by Django 4.0.5 on 2022-07-25 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('french', '0008_remove_quote_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FrenchLesson',
        ),
    ]
