# Generated by Django 4.0.5 on 2022-08-21 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('french', '0011_alter_quote_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='page',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
