# Generated by Django 4.0.5 on 2022-07-23 10:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('english', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.card')),
            ],
        ),
        migrations.CreateModel(
            name='EnglishLessonProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.IntegerField(default=1)),
                ('cards', models.ManyToManyField(to='users.cardprofile')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='english.englishlesson')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lessons_english', models.ManyToManyField(blank=True, to='users.englishlessonprofile')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('share_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('admins', models.ManyToManyField(related_name='%(class)s_admin', to=settings.AUTH_USER_MODEL)),
                ('lessons_english', models.ManyToManyField(blank=True, to='english.englishlesson')),
                ('super_admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('users', models.ManyToManyField(related_name='%(class)s_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
