# Generated by Django 4.0.5 on 2022-07-24 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('french', '0004_quote_active'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='quotes',
            field=models.ManyToManyField(blank=True, to='french.quote'),
        ),
    ]
