# Generated by Django 4.0.5 on 2022-07-24 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('french', '0008_remove_quote_active'),
        ('users', '0002_group_quotes'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=True)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='french.quote')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='quotes',
            field=models.ManyToManyField(blank=True, to='users.quoteprofile'),
        ),
    ]
