# Generated by Django 4.0.5 on 2022-08-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_quotetag_quoteprofile_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteprofile',
            name='tags',
            field=models.ManyToManyField(blank=True, to='users.quotetag'),
        ),
    ]
