# Generated by Django 4.0.5 on 2022-07-23 10:49

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField()),
                ('text2', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='EnglishLesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('share_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('date', models.DateTimeField(default=datetime.datetime(2022, 7, 23, 12, 49, 20, 93495), editable=False)),
                ('title', models.CharField(max_length=50)),
                ('key', models.IntegerField(default=1)),
                ('access', models.ManyToManyField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_user_english', to=settings.AUTH_USER_MODEL), related_name='access_user_english', to=settings.AUTH_USER_MODEL)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_user_english', to=settings.AUTH_USER_MODEL)),
                ('cards', models.ManyToManyField(to='english.card')),
            ],
        ),
    ]
