# Generated by Django 4.0.5 on 2022-07-23 14:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0003_alter_englishlesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishlesson',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 23, 16, 35, 22, 402391), editable=False),
        ),
    ]
