# Generated by Django 4.0.5 on 2022-07-24 09:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0004_alter_englishlesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishlesson',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 11, 41, 16, 691597), editable=False),
        ),
    ]
