# Generated by Django 4.0.5 on 2022-07-24 10:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0007_alter_englishlesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishlesson',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 24, 12, 6, 3, 242688), editable=False),
        ),
    ]
