# Generated by Django 4.0.5 on 2022-07-25 10:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0009_alter_englishlesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishlesson',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 12, 17, 4, 110495), editable=False),
        ),
    ]
