# Generated by Django 4.0.5 on 2022-07-29 11:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0010_alter_englishlesson_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishlesson',
            name='key',
        ),
        migrations.AlterField(
            model_name='englishlesson',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 13, 9, 4, 291885), editable=False),
        ),
    ]
