# Generated by Django 4.0.5 on 2022-07-29 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0011_remove_englishlesson_key_alter_englishlesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishlesson',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 29, 13, 14, 59, 3298), editable=False),
        ),
    ]
