# Generated by Django 4.0.5 on 2022-08-01 09:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0013_alter_englishlesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishlesson',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 1, 11, 49, 50, 64361), editable=False),
        ),
    ]
