# Generated by Django 4.0.5 on 2022-08-02 13:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0015_alter_englishlesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishlesson',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 2, 15, 59, 14, 234945), editable=False),
        ),
    ]
