# Generated by Django 4.0.5 on 2022-08-21 16:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0016_alter_englishlesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishlesson',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 21, 18, 18, 36, 384258), editable=False),
        ),
    ]
