# Generated by Django 4.0.5 on 2024-08-13 13:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('english', '0018_alter_englishlesson_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishlesson',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2024, 8, 13, 15, 33, 48, 891692), editable=False),
        ),
    ]
